---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: qperf
  name: client
  labels:
    app: qperf-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qperf-client
  template:
    metadata:
      labels:
        app: qperf-client
    spec:
      containers:
      - name: qperf-client
        image: danielcoman/docker-qperf:latest
        env:
        - name: SERVICE_TYPE
          value: "ping"
        - name: SERVER_ADDR
          value: "server.qperf.svc.cluster.local"
        - name: SERVER_PORT
          value: "443"
        - name: QPERF_INTERVAL
          value: "10-60" # shuf range
